from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DecimalType

# Define schema
schema = StructType([
    StructField("reference_pool_id", StringType()),
    StructField("loan_identifier", StringType()),
    StructField("monthly_reporting_period", StringType()),
    StructField("channel", StringType()),
    StructField("seller_name", StringType()),
    StructField("servicer_name", StringType()),
    StructField("master_servicer", StringType()),
    StructField("original_interest_rate", DecimalType(5, 3)),
    StructField("current_interest_rate", DecimalType(5, 3)),
    StructField("original_upb", DecimalType(12, 2)),
    StructField("upb_at_issuance", DecimalType(12, 2)),
    StructField("current_actual_upb", DecimalType(12, 2)),
    StructField("original_loan_term", IntegerType()),
    StructField("origination_date", StringType()),
    StructField("first_payment_date", StringType()),
    StructField("loan_age", IntegerType()),
    StructField("remaining_months_to_legal_maturity", IntegerType()),
    StructField("remaining_months_to_maturity", IntegerType()),
    StructField("maturity_date", StringType()),
    StructField("oltv", IntegerType()),
    StructField("ocltv", IntegerType()),
    StructField("number_of_borrowers", IntegerType()),
    StructField("dti", IntegerType()),
    StructField("borrower_credit_score_at_origination", IntegerType()),
    StructField("coborrower_credit_score_at_origination", IntegerType()),
    StructField("first_time_home_buyer_indicator", StringType()),
    StructField("loan_purpose", StringType()),
    StructField("property_type", StringType()),
    StructField("number_of_units", IntegerType()),
    StructField("occupancy_status", StringType()),
    StructField("property_state", StringType()),
    StructField("msa", StringType()),
    StructField("zip_code_short", StringType()),
    StructField("mortgage_insurance_percentage", DecimalType(6, 3)),
    StructField("amortization_type", StringType()),
    StructField("prepayment_penalty_indicator", StringType()),
    StructField("interest_only_loan_indicator", StringType()),
    StructField("interest_only_first_principal_and_interest_payment_date", StringType()),
    StructField("months_to_amortization", IntegerType()),
    StructField("current_loan_delinquency_status", StringType()),
    StructField("loan_payment_history", StringType()),
    StructField("modification_flag", StringType()),
    StructField("mortgage_insurance_cancellation_indicator", StringType()),
    StructField("zero_balance_code", StringType()),
    StructField("zero_balance_effective_date", StringType()),
    StructField("upb_at_the_time_of_removal", DecimalType(12, 2)),
    StructField("repurchase_date", StringType()),
    StructField("scheduled_principal_current", DecimalType(12, 2)),
    StructField("total_principal_current", DecimalType(12, 2)),
    StructField("unscheduled_principal_current", DecimalType(12, 2)),
    StructField("last_paid_installment_date", StringType()),
    StructField("foreclosure_date", StringType()),
    StructField("disposition_date", StringType()),
    StructField("foreclosure_costs", DecimalType(12, 2)),
    StructField("property_preservation_and_repair_costs", DecimalType(12, 2)),
    StructField("asset_recovery_costs", DecimalType(12, 2)),
    StructField("miscellaneous_holding_expenses_and_credits", DecimalType(12, 2)),
    StructField("associated_taxes_for_holding_property", DecimalType(12, 2)),
    StructField("net_sales_proceeds", DecimalType(12, 2)),
    StructField("credit_enhancement_proceeds", DecimalType(12, 2)),
    StructField("repurchase_make_whole_proceeds", DecimalType(12, 2)),
    StructField("other_foreclosure_proceeds", DecimalType(12, 2)),
    StructField("modification_related_non_interest_bearing_upb", DecimalType(12, 2)),
    StructField("principal_forgiveness_amount", DecimalType(12, 2)),
    StructField("original_list_start_date", StringType()),
    StructField("original_list_price", DecimalType(12, 2)),
    StructField("current_list_start_date", StringType()),
    StructField("current_list_price", DecimalType(12, 2)),
    StructField("borrower_credit_score_at_issuance", IntegerType()),
    StructField("coborrower_credit_score_at_issuance", IntegerType()),
    StructField("borrower_credit_score_current", IntegerType()),
    StructField("coborrower_credit_score_current", IntegerType()),
    StructField("mortgage_insurance_type", StringType()),
    StructField("servicing_activity_indicator", StringType()),
    StructField("current_period_modification_loss_amount", DecimalType(12, 2)),
    StructField("cumulative_modification_loss_amount", DecimalType(12, 2)),
    StructField("current_period_credit_event_net_gain_or_loss", DecimalType(12, 2)),
    StructField("cumulative_credit_event_net_gain_or_loss", DecimalType(12, 2)),
    StructField("special_eligibility_program", StringType()),
    StructField("foreclosure_principal_write_off_amount", DecimalType(12, 2)),
    StructField("relocation_mortgage_indicator", StringType()),
    StructField("zero_balance_code_change_date", StringType()),
    StructField("loan_holdback_indicator", StringType()),
    StructField("loan_holdback_effective_date", StringType()),
    StructField("delinquent_accrued_interest", DecimalType(12, 2)),
    StructField("property_valuation_method", StringType()),
    StructField("high_balance_loan_indicator", StringType()),
    StructField("arm_initial_fixed_rate_period", StringType()),
    StructField("arm_product_type", StringType()),
    StructField("initial_fixed_rate_period", IntegerType()),
    StructField("interest_rate_adjustment_frequency", IntegerType()),
    StructField("next_interest_rate_adjustment_date", StringType()),
    StructField("next_payment_change_date", StringType()),
    StructField("index", StringType()),
    StructField("arm_cap_structure", StringType()),
    StructField("initial_interest_rate_cap_up_percent", DecimalType(6, 4)),
    StructField("periodic_interest_rate_cap_up_percent", DecimalType(6, 4)),
    StructField("lifetime_interest_rate_cap_up_percent", DecimalType(6, 4)),
    StructField("mortgage_margin", DecimalType(9, 4)),
    StructField("arm_balloon_indicator", StringType()),
    StructField("arm_plan_number", IntegerType()),
    StructField("borrower_assistance_plan", StringType()),
    StructField("hltv", StringType()),
    StructField("deal_name", StringType()),
    StructField("repurchase_make_whole_proceeds_flag", StringType()),
    StructField("alternative_delinquency_resolution", StringType()),
    StructField("alternative_delinquency_resolution_count", IntegerType()),
    StructField("total_deferral_amount", DecimalType(12, 2)),
    StructField("payment_deferral_modification_event_indicator", StringType()),
    StructField("interest_bearing_upb", DecimalType(12, 2))
])
