LOAD DATA OVERWRITE {dataset_name}.{security_name}
(reference_pool_id STRING,
loan_identifier STRING,
monthly_reporting_period STRING,
channel STRING,
seller_name STRING,
servicer_name STRING,
master_servicer STRING,
original_interest_rate NUMERIC(5, 3),
current_interest_rate NUMERIC(5, 3),
original_upb NUMERIC(12, 2),
upb_at_issuance NUMERIC(12, 2),
current_actual_upb NUMERIC(12, 2),
original_loan_term INT,
origination_date STRING,
first_payment_date STRING,
loan_age INT,
remaining_months_to_legal_maturity INT,
remaining_months_to_maturity INT,
maturity_date STRING,
oltv INT,
ocltv INT,
number_of_borrowers INT,
dti INT,
borrower_credit_score_at_origination INT,
coborrower_credit_score_at_origination INT,
first_time_home_buyer_indicator STRING,
loan_purpose STRING,
property_type STRING,
number_of_units INT,
occupancy_status STRING,
property_state STRING,
msa STRING,
zip_code_short STRING,
mortgage_insurance_percentage NUMERIC(6, 3),
amortization_type STRING,
prepayment_penalty_indicator STRING,
interest_only_loan_indicator STRING,
interest_only_first_principal_and_interest_payment_date STRING,
months_to_amortization INT,
current_loan_delinquency_status STRING,
loan_payment_history STRING,
modification_flag STRING,
mortgage_insurance_cancellation_indicator STRING,
zero_balance_code STRING,
zero_balance_effective_date STRING,
upb_at_the_time_of_removal NUMERIC(12, 2),
repurchase_date STRING,
scheduled_principal_current NUMERIC(12, 2),
total_principal_current NUMERIC(12, 2),
unscheduled_principal_current NUMERIC(12, 2),
last_paid_installment_date STRING,
foreclosure_date STRING,
disposition_date STRING,
foreclosure_costs NUMERIC(12, 2),
property_preservation_and_repair_costs NUMERIC(12, 2),
asset_recovery_costs NUMERIC(12, 2),
miscellaneous_holding_expenses_and_credits NUMERIC(12, 2),
associated_taxes_for_holding_property NUMERIC(12, 2),
net_sales_proceeds NUMERIC(12, 2),
credit_enhancement_proceeds NUMERIC(12, 2),
repurchase_make_whole_proceeds NUMERIC(12, 2),
other_foreclosure_proceeds NUMERIC(12, 2),
modification_related_non_interest_bearing_upb NUMERIC(12, 2),
principal_forgiveness_amount NUMERIC(12, 2),
original_list_start_date STRING,
original_list_price NUMERIC(12, 2),
current_list_start_date STRING,
current_list_price NUMERIC(12, 2),
borrower_credit_score_at_issuance INT,
coborrower_credit_score_at_issuance INT,
borrower_credit_score_current INT,
coborrower_credit_score_current INT,
mortgage_insurance_type STRING,
servicing_activity_indicator STRING,
current_period_modification_loss_amount NUMERIC(12, 2),
cumulative_modification_loss_amount NUMERIC(12, 2),
current_period_credit_event_net_gain_or_loss NUMERIC(12, 2),
cumulative_credit_event_net_gain_or_loss NUMERIC(12, 2),
special_eligibility_program STRING,
foreclosure_principal_write_off_amount NUMERIC(12, 2),
relocation_mortgage_indicator STRING,
zero_balance_code_change_date STRING,
loan_holdback_indicator STRING,
loan_holdback_effective_date STRING,
delinquent_accrued_interest NUMERIC(12, 2),
property_valuation_method STRING,
high_balance_loan_indicator STRING,
arm_initial_fixed_rate_period STRING,
arm_product_type STRING,
initial_fixed_rate_period INT,
interest_rate_adjustment_frequency INT,
next_interest_rate_adjustment_date STRING,
next_payment_change_date STRING,
index STRING,
arm_cap_structure STRING,
initial_interest_rate_cap_up_percent NUMERIC(6, 4),
periodic_interest_rate_cap_up_percent NUMERIC(6, 4),
lifetime_interest_rate_cap_up_percent NUMERIC(6, 4),
mortgage_margin NUMERIC(9, 4),
arm_balloon_indicator STRING,
arm_plan_number INT,
borrower_assistance_plan STRING,
hltv STRING,
deal_name STRING,
repurchase_make_whole_proceeds_flag STRING,
alternative_delinquency_resolution STRING,
alternative_delinquency_resolution_count INT,
total_deferral_amount NUMERIC(12, 2),
payment_deferral_modification_event_indicator STRING,
interest_bearing_upb NUMERIC(12, 2)
)
FROM FILES (
  format = 'CSV',
  field_delimiter = '|',
  uris = ['gs://{your-bucket}/{folder}/*.csv']);